const products = [
    {
        _id: "1",
        name: "Iphone",
        image: "/images/Iphone.jpeg",
        description: "Iphone description",
        brand: "Apple",
        category: "Electronics",
        price: 1099.99,
        countInStock: 10,
        rating: 4.5,
        numReviews: 12,
    },
    {
        _id: "2",
        name: "iPad",
        image: "/images/Ipad.jpeg",
        description: "iPad description",
        brand: "Apple",
        category: "Electronics",
        price: 799.99,
        countInStock: 15,
        rating: 4.7,
        numReviews: 18,
    },
    {
        _id: "3",
        name: "Smartwatch",
        image: "/images/watch.jpeg",
        description: "Smartwatch description",
        brand: "Samsung",
        category: "Electronics",
        price: 299.99,
        countInStock: 8,
        rating: 4.2,
        numReviews: 9,
    },
    {
        _id: "4",
        name: "AirPods",
        image: "/images/airpods.jpeg",
        description: "AirPods description",
        brand: "Apple",
        category: "Electronics",
        price: 199.99,
        countInStock: 20,
        rating: 4.8,
        numReviews: 15,
    },
    {
        _id: "5",
        name: "MacBook Pro",
        image: "/images/mac.jpeg",
        description: "MacBook Pro description",
        brand: "Apple",
        category: "Electronics",
        price: 1499.99,
        countInStock: 7,
        rating: 4.9,
        numReviews: 22,
    },
];

export default products;
